export const texts = {
  sk: {
    nav: {
      about: 'O mne',
      skills: 'Zručnosti',
      work: 'Práce',
      contact: 'Kontakt',
    },
    hero: {
      stamp: 'K dispozícii na spoluprácu · 2026',
      greeting: 'Ahoj, som',
      name: 'Matej.',
      tagline: 'Tvorím softvér.',
      lede: 'Študent informatiky a manažmentu na FRI UNIZA v Žiline. Zameriavam sa na vývoj softvéru, návrh systémov v UML a prácu s Oracle SQL.',
      ctaPrimary: 'Pozri moje práce',
      ctaSecondary: 'Napíš mi',
      metaLocation: 'Žilina, Slovensko',
      metaSchool: 'FRI UNIZA · 2026',
      card: {
        roleLabel: 'Rola',
        roleValue: 'Študent informatiky',
        schoolLabel: 'Škola',
        schoolValue: 'FRI UNIZA',
        focusLabel: 'Zameranie',
        focusValue: 'Softvér · UML · SQL',
        sinceLabel: 'Od',
        sinceValue: '2023',
        statusLabel: 'Status',
        statusValue: '● otvorený pre prácu',
        idLine: 'ID',
        subtitle: 'študent · vývojár · Žilina, SK',
      },
      mobile: {
        bootConnecting: 'pripájanie',
        bootLoading: 'načítavam',
        bootStatus: 'status: dostupný',
        bootWelcome: 'vitaj — posúvaj nadol pre viac',
        available: 'Dostupný 2026',
        bio: 'Študent informatiky a manažmentu na FRI UNIZA. Tvorím softvér, navrhujem systémy, píšem SQL.',
        infoSchool: 'Škola',
        infoFocus: 'Zameranie',
        infoBased: 'Sídlo',
        infoStatus: 'Status',
        scrollHint: 'posúvaj',
      },
    },
    about: {
      sectionLabel: 'O mne',
      title: 'Krátky',
      titleAccent: 'úvod.',
      sub: 'Skrátka: cez deň študent, večer staviteľ. Zaujíma ma, ako sa softvér navrhuje, štruktúruje a používa.',
      lede: 'Som študent informatiky a manažmentu na FRI UNIZA v Žiline so zameraním na vývoj softvéru, návrh systémov (UML) a databázy.',
      p2: 'Baví ma kombinovať logiku s prezentáciou — backend so zmysluplnou štruktúrou, ale aj frontend, postery a UI ktoré rešpektujú čitateľa. Väčšina prác nižšie pochádza zo semestrálnych zadaní a osobných experimentov.',
      p3: 'Mimo klávesnice ma baví dizajn, šport a nové výzvy — veci sa učím rýchlo a rád dokončujem to, čo začnem.',
      facts: {
        name: 'Meno',
        nameValue: 'Matej Roháč',
        location: 'Lokalita',
        locationValue: 'Žilina, SK',
        university: 'Univerzita',
        universityValue: 'FRI UNIZA',
        field: 'Odbor',
        fieldValue: 'Informatika a manažment',
        focus: 'Zameranie',
        focusValue: 'Softvér · UML · SQL',
        status: 'Status',
        statusValue: '● Dostupný',
        languages: 'Jazyky',
        languagesValue: 'SK · EN',
        year: 'Rok',
        yearValue: '2026',
      },
    },
    skills: {
      sectionLabel: 'Zručnosti',
      title: 'Čo',
      titleAccent: 'ovládam.',
      sub: 'Mix nástrojov pre vývoj softvéru, návrh systémov a vizuálnu prácu.',
      notes: {
        uml: 'návrh systémov, diagramy',
        office: 'Word · Excel · PowerPoint',
        sql: 'dopyty, návrh schémy',
        java: 'OOP, malé desktop apky',
        canva: 'rýchle vizuály, postery',
        photoshop: 'retuš, layout',
        figma: 'UI dizajn, prototypy',
        kotlin: 'Android, skripty',
        react: 'komponenty, state',
      },
    },
    work: {
      sectionLabel: 'Práce',
      title: 'Vybrané',
      titleAccent: 'projekty.',
      sub: 'Krátke ukážky mojej práce — väčšinou semestrálne zadania a pár osobných experimentov.',
      items: {
        survivor: {
          desc: 'Survivor je semestrálny projekt vytvorený v Jave, inšpirovaný hrou Crossy Road.',
        },
        warOfClash: {
          desc: 'WarOfClash je semestrálny projekt v Jave — real-time stratégia inšpirovaná hrou Clash Royale.',
        },
        pathPulse: {
          desc: 'PathPulse je semestrálny Kotlin projekt pre cestovateľov, ktorí si radi sledujú svoje výlety.',
        },
        invitation: {
          desc: 'Pozvánka na 3. edukačné podujatie pre pacientov s kardiovaskulárnym ochorením. Na zákazku klienta (Kardiocentrum Nitra).',
        },
        designs: {
          desc: 'Moja obľúbená časť školskej práce — dizajny prezentácií.',
        },
      },
    },
    contact: {
      sectionLabel: 'Kontakt',
      title: 'Poďme sa',
      titleAccent: 'porozprávať.',
      sub: 'Otvorený pre stáže, spolupráce a vedľajšie projekty okolo softvéru, návrhu systémov v UML a databáz. Email je najrýchlejší — väčšinou odpovedám do dňa.',
      links: {
        email: 'Email',
        github: 'GitHub',
        linkedin: 'LinkedIn',
        instagram: 'Instagram',
      },
    },
    footer: {
      built: 'Postavené v React · Vite',
      version: 'v2',
    },
  },
  en: {
    nav: {
      about: 'About',
      skills: 'Skills',
      work: 'Work',
      contact: 'Contact',
    },
    hero: {
      stamp: 'Available for collaboration · 2026',
      greeting: "Hi, I'm",
      name: 'Matej.',
      tagline: 'I build software.',
      lede: 'Computer Science and Management student at FRI UNIZA in Žilina. Focused on software development, system design with UML, and Oracle SQL.',
      ctaPrimary: 'See my work',
      ctaSecondary: 'Get in touch',
      metaLocation: 'Žilina, Slovakia',
      metaSchool: 'FRI UNIZA · 2026',
      card: {
        roleLabel: 'Role',
        roleValue: 'CS Student',
        schoolLabel: 'School',
        schoolValue: 'FRI UNIZA',
        focusLabel: 'Focus',
        focusValue: 'Software · UML · SQL',
        sinceLabel: 'Since',
        sinceValue: '2023',
        statusLabel: 'Status',
        statusValue: '● open to work',
        idLine: 'ID',
        subtitle: 'student · developer · Žilina, SK',
      },
      mobile: {
        bootConnecting: 'connecting',
        bootLoading: 'loading',
        bootStatus: 'status: available',
        bootWelcome: 'welcome — scroll to explore',
        available: 'Available 2026',
        bio: 'CS & Management student at FRI UNIZA. Building software, designing systems, writing SQL.',
        infoSchool: 'School',
        infoFocus: 'Focus',
        infoBased: 'Based',
        infoStatus: 'Status',
        scrollHint: 'scroll',
      },
    },
    about: {
      sectionLabel: 'About',
      title: 'A quick',
      titleAccent: 'intro.',
      sub: 'Short version: student by day, builder by evening. Curious about how software is designed, structured and used.',
      lede: "I'm a Computer Science and Management student at FRI UNIZA in Žilina, focused on software development, system design (UML) and databases.",
      p2: 'I enjoy projects that mix logic with presentation — backend that is well-structured but also front-ends, posters and UI that actually respect the reader. Most of the work below is from semester assignments and personal experiments.',
      p3: "Outside the keyboard I'm into design, sports and new challenges — I pick things up fast and I like to finish what I start.",
      facts: {
        name: 'Name',
        nameValue: 'Matej Roháč',
        location: 'Location',
        locationValue: 'Žilina, SK',
        university: 'University',
        universityValue: 'FRI UNIZA',
        field: 'Field',
        fieldValue: 'CS & Management',
        focus: 'Focus',
        focusValue: 'Software · UML · SQL',
        status: 'Status',
        statusValue: '● Available',
        languages: 'Languages',
        languagesValue: 'SK · EN',
        year: 'Year',
        yearValue: '2026',
      },
    },
    skills: {
      sectionLabel: 'Skills',
      title: 'What I',
      titleAccent: 'know.',
      sub: 'A mix of tools for software development, system design and visual work.',
      notes: {
        uml: 'system design, diagrams',
        office: 'Word · Excel · PowerPoint',
        sql: 'queries, schema design',
        java: 'OOP, small desktop apps',
        canva: 'quick visuals, posters',
        photoshop: 'retouching, layout',
        figma: 'UI design, prototyping',
        kotlin: 'Android, scripting',
        react: 'components, state',
      },
    },
    work: {
      sectionLabel: 'Work',
      title: 'Selected',
      titleAccent: 'projects.',
      sub: 'Short examples of my work — mostly semester assignments and a few personal experiments.',
      items: {
        survivor: {
          desc: 'Survivor is a semester project built in Java, inspired by the game Crossy Road.',
        },
        warOfClash: {
          desc: 'WarOfClash is a semester project in Java — a real-time strategy game inspired by Clash Royale.',
        },
        pathPulse: {
          desc: 'PathPulse is a semester Kotlin project created for travelers who like to track their journeys.',
        },
        invitation: {
          desc: 'Invitation to the 3rd Educational Event for Patients with Cardiovascular Disease. Created at the request of the client (Kardiocentrum Nitra).',
        },
        designs: {
          desc: 'My favourite part of school work — designs of my presentations.',
        },
      },
    },
    contact: {
      sectionLabel: 'Contact',
      title: "Let's",
      titleAccent: 'talk.',
      sub: 'Open to internships, collaborations and side projects around software, UML system design and databases. Email is fastest — I usually reply within a day.',
      links: {
        email: 'Email',
        github: 'GitHub',
        linkedin: 'LinkedIn',
        instagram: 'Instagram',
      },
    },
    footer: {
      built: 'Built in React · Vite',
      version: 'v2',
    },
  },
}
