export const texts = {
  sk: {
    nav: {
      about: "O mne",
      work: "Práce",
      contact: "Kontakt",
    },
    hero: {
      stamp: "K dispozícii na spoluprácu · 2026",
      greeting: "Ahoj, som",
      name: "Matej.",
      tagline: "Tvorím softvér.",
      lede: "Študent informatiky a manažmentu na FRI UNIZA v Žiline. Zameriavam sa na vývoj softvéru, návrh systémov v UML a prácu s Oracle SQL.",
      ctaPrimary: "Pozri moje práce",
      ctaSecondary: "Napíš mi",
      metaLocation: "Žilina, Slovensko",
      metaSchool: "FRI UNIZA · 2026",
      card: {
        roleLabel: "Rola",
        roleValue: "Študent informatiky",
        schoolLabel: "Škola",
        schoolValue: "FRI UNIZA",
        focusLabel: "Zameranie",
        focusValue: "Softvér · Testovanie · Redizajn",
        experienceLabel: "Skúsenosti",
        experienceValue: "Stáže v Goldmann Systems, Multitude",
        statusLabel: "Status",
        statusValue: "● otvorený pre prácu",
        idLine: "ID",
        subtitle: "študent · vývojár · Žilina, SK",
      },
      mobile: {
        bootConnecting: "pripájanie",
        bootLoading: "načítavam",
        bootStatus: "status: dostupný",
        bootWelcome: "vitaj — posúvaj nadol pre viac",
        available: "Dostupný 2026",
        bio: "Študent informatiky a manažmentu na FRI UNIZA. Tvorím softvér, navrhujem systémy, píšem SQL.",
        infoSchool: "Škola",
        infoFocus: "Zameranie",
        infoBased: "Sídlo",
        infoStatus: "Status",
        scrollHint: "posúvaj",
      },
    },
    about: {
      sectionLabel: "O mne",
      title: "Krátky",
      titleAccent: "úvod.",
      sub: "Skrátka: cez deň študent, večer staviteľ. Zaujíma ma, ako sa softvér navrhuje, štruktúruje a používa.",
      lede: "Som študent informatiky a manažmentu na FRI UNIZA v Žiline so zameraním na vývoj softvéru, návrh systémov (UML) a databázy.",
      p2: "Baví ma kombinovať logiku s prezentáciou — backend so zmysluplnou štruktúrou, ale aj frontend, postery a UI ktoré rešpektujú čitateľa. Väčšina prác nižšie pochádza zo semestrálnych zadaní a osobných experimentov.",
      p3: "Mimo klávesnice ma baví dizajn, šport a nové výzvy — veci sa učím rýchlo a rád dokončujem to, čo začnem.",
      facts: {
        name: "Meno",
        nameValue: "Matej Roháč",
        location: "Lokalita",
        locationValue: "Žilina, SK",
        university: "Univerzita",
        universityValue: "FRI UNIZA",
        field: "Odbor",
        fieldValue: "Informatika a manažment",
        focus: "Zameranie",
        focusValue: "Softvér · UML · SQL",
        status: "Status",
        statusValue: "● Dostupný",
        languages: "Jazyky",
        languagesValue: "SK · EN",
        year: "Rok",
        yearValue: "2026",
      },
    },
    work: {
      sectionLabel: "Práce",
      title: "Vybrané",
      titleAccent: "projekty.",
      sub: "Krátke ukážky mojej práce — väčšinou semestrálne zadania a pár osobných experimentov.",
      items: {
        survivor: {
          cat: "Java · Hra",
          title: "Survivor",
          desc: "Semestrálny projekt v Jave, inšpirovaný hrou Crossy Road.",
          year: "2023",
        },
        warOfClash: {
          cat: "Java · Stratégia",
          title: "WarOfClash",
          desc: "Real-time stratégia v Jave inšpirovaná hrou Clash Royale.",
          year: "2024",
        },
        pathPulse: {
          cat: "Kotlin · Mobile",
          title: "PathPulse",
          desc: "Kotlin projekt pre cestovateľov, ktorí si radi sledujú svoje výlety.",
          year: "2025",
        },
        invitation: {
          cat: "Print · Healthcare",
          title: "Pozvánka",
          desc: "Pozvánka na 3. edukačné podujatie pre pacientov s kardiovaskulárnym ochorením. Klient: Kardiocentrum Nitra.",
          year: "2025",
        },
      },
    },
    contact: {
      sectionLabel: "Kontakt",
      title: "Poďme sa",
      titleAccent: "porozprávať.",
      sub: "Otvorený pre stáže aj klientske projekty. Ak potrebuješ web, systém alebo pomoc s vývojom, som tu.",
      whyMe: {
        label: "PREČO JA",
        title: "Menej slov,",
        titleAccent: "viac výsledkov.",
        lede: "Tri krátke dôvody predtým ako napíšeš.",
        perks: [
          {
            title: "Najprv návrh, potom kód",
            desc: "Každý projekt začína vizuálom. Sadneme si nad návrh, odsúhlasíme smer a až potom sa píše prvý riadok kódu. Žiadne prekvapenia.",
          },
          {
            title: "Priebežne v obraze",
            desc: "Počas vývoja dostávaš pravidelné updaty. Vieš čo je hotové a čo je ďalej. Žiadne ticho na týždne.",
          },
          {
            title: "Silné základy zo školy",
            desc: "UML, databázy, testovanie, softvérové inžinierstvo. Nie samouk z tutoriálov, ale systematické vzdelanie, ktoré sa prejaví v kvalite kódu.",
          },
        ],
      },
      form: {
        label: "NAPÍŠ MI",
        title: "Povedz mi o viac.",
        nameLabel: "MENO",
        namePlaceholder: "Tvoje meno",
        emailLabel: "EMAIL",
        emailPlaceholder: "ty@firma.sk",
        topicLabel: "TÉMA",
        topicOptions: ["Web na mieru", "Systém na mieru", "Redizajn existujúceho webu", "Pracovná ponuka", "Iné"],
        messageLabel: "SPRÁVA",
        messagePlaceholder: "Pár riadkov o tom, čo staviaš.",
        sendButton: "Poslať správu →",
        emailAddress: "matej.rohac24@gmail.com",
      },
    },
    footer: {
      built: "Postavené v React · Vite",
      version: "v2",
    },
  },
  en: {
    nav: {
      about: "About",
      work: "Work",
      contact: "Contact",
    },
    hero: {
      stamp: "Available for collaboration · 2026",
      greeting: "Hi, I'm",
      name: "Matej.",
      tagline: "I build software.",
      lede: "Computer Science and Management student at FRI UNIZA in Žilina. Focused on software development, system design with UML, and Oracle SQL.",
      ctaPrimary: "See my work",
      ctaSecondary: "Get in touch",
      metaLocation: "Žilina, Slovakia",
      metaSchool: "FRI UNIZA · 2026",
      card: {
        roleLabel: "Role",
        roleValue: "Student",
        schoolLabel: "School",
        schoolValue: "FRI UNIZA",
        focusLabel: "Focus",
        focusValue: "Software · Testing · Redesign",
        experienceLabel: "Experience",
        experienceValue: "Internships at Goldmann Systems, Multitude",
        statusLabel: "Status",
        statusValue: "● open to work",
        idLine: "ID",
        subtitle: "student · developer · Žilina, SK",
      },
      mobile: {
        bootConnecting: "connecting",
        bootLoading: "loading",
        bootStatus: "status: available",
        bootWelcome: "welcome — scroll to explore",
        available: "Available 2026",
        bio: "CS & Management student at FRI UNIZA. Building software, designing systems, writing SQL.",
        infoSchool: "School",
        infoFocus: "Focus",
        infoBased: "Based",
        infoStatus: "Status",
        scrollHint: "scroll",
      },
    },
    about: {
      sectionLabel: "About",
      title: "A quick",
      titleAccent: "intro.",
      sub: "Short version: student by day, builder by evening. Curious about how software is designed, structured and used.",
      lede: "I'm a Computer Science and Management student at FRI UNIZA in Žilina, focused on software development, system design (UML) and databases.",
      p2: "I enjoy projects that mix logic with presentation — backend that is well-structured but also front-ends, posters and UI that actually respect the reader. Most of the work below is from semester assignments and personal experiments.",
      p3: "Outside the keyboard I'm into design, sports and new challenges — I pick things up fast and I like to finish what I start.",
      facts: {
        name: "Name",
        nameValue: "Matej Roháč",
        location: "Location",
        locationValue: "Žilina, SK",
        university: "University",
        universityValue: "FRI UNIZA",
        field: "Field",
        fieldValue: "CS & Management",
        focus: "Focus",
        focusValue: "Software · UML · SQL",
        status: "Status",
        statusValue: "● Available",
        languages: "Languages",
        languagesValue: "SK · EN",
        year: "Year",
        yearValue: "2026",
      },
    },
    work: {
      sectionLabel: "Work",
      title: "Selected",
      titleAccent: "projects.",
      sub: "Short examples of my work — mostly semester assignments and a few personal experiments.",
      items: {
        survivor: {
          cat: "Java · Game",
          title: "Survivor",
          desc: "A semester project in Java, inspired by the game Crossy Road.",
          year: "2023",
        },
        warOfClash: {
          cat: "Java · Strategy",
          title: "WarOfClash",
          desc: "A real-time strategy in Java inspired by Clash Royale.",
          year: "2024",
        },
        pathPulse: {
          cat: "Kotlin · Mobile",
          title: "PathPulse",
          desc: "A Kotlin project for travelers who like to track their journeys.",
          year: "2025",
        },
        invitation: {
          cat: "Print · Healthcare",
          title: "Invitation",
          desc: "Invitation to the 3rd Educational Event for Patients with Cardiovascular Disease. Client: Kardiocentrum Nitra.",
          year: "2025",
        },
      },
    },
    contact: {
      sectionLabel: "Contact",
      title: "Let's",
      titleAccent: "talk.",
      sub: "Open to internships and client projects. If you need a website, a system or help with development, I'm here.",
      whyMe: {
        label: "WHY ME",
        title: "Fewer words,",
        titleAccent: "more results.",
        lede: "Three short reasons before you write.",
        perks: [
          {
            title: "Design first, then code",
            desc: "Every project starts with a plan. We sit down, look at the design, agree on the direction, and only then I write the first line of code. No surprises.",
          },
          {
            title: "Always in the loop",
            desc: "During the work you get regular updates. You know what is done and what comes next. No silence for weeks.",
          },
          {
            title: "Strong school basics",
            desc: "UML, databases, testing, software engineering. Not self-taught from tutorials, but real school knowledge that shows in the code quality.",
          },
        ],
      },
      form: {
        label: "SEND A MESSAGE",
        title: "Tell me more.",
        nameLabel: "NAME",
        namePlaceholder: "Your name",
        emailLabel: "EMAIL",
        emailPlaceholder: "you@company.com",
        topicLabel: "TOPIC",
        topicOptions: ["Custom website", "Custom system", "Website redesign", "Job offer", "Other"],
        messageLabel: "MESSAGE",
        messagePlaceholder: "A few lines about what you're building.",
        sendButton: "Send message →",
        emailAddress: "matej.rohac24@gmail.com",
      },
    },
    footer: {
      built: "Built in React · Vite",
      version: "v2",
    },
  },
};
